import { FundManager } from './types';

export const managers: FundManager[] = [
  {
    id: '1',
    name: '刘旭',
    fundName: '大成高新技术产业A',
    fundCode: '000628',
    years: 10.2,
    annualizedReturn: 16.8,
    maxDrawdown: -25.4,
    philosophy: '深度价值，自下而上精选个股，注重安全边际',
    stockSelectionLogic: '极度看重自由现金流和护城河，偏好制造业，买入并长期持有，不追逐短期热点。',
    holdings: ['格力电器', '美的集团', '豪迈科技'],
    tradingMethod: '场外',
    isTop3: true,
  },
  {
    id: '2',
    name: '周云',
    fundName: '东方红京东大数据A',
    fundCode: '001564',
    years: 10.1,
    annualizedReturn: 15.5,
    maxDrawdown: -26.1,
    philosophy: '逆向投资，绝对收益导向，严格控制回撤',
    stockSelectionLogic: '寻找均值回归的机会，在市场悲观时买入低估值优质资产，注重PB-ROE的匹配度。',
    holdings: ['立讯精密', '伊利股份', '海康威视'],
    tradingMethod: '场外',
    isTop3: true,
  },
  {
    id: '3',
    name: '鲍无可',
    fundName: '景顺长城能源基建A',
    fundCode: '260112',
    years: 11.5,
    annualizedReturn: 15.6,
    maxDrawdown: -26.8,
    philosophy: '绝对收益理念，寻找高壁垒、低估值',
    stockSelectionLogic: '寻找具有高安全边际的优质企业，极度厌恶资本永久性损失的风险，偏好公用事业与能源。',
    holdings: ['川投能源', '中南传媒', '紫金矿业'],
    tradingMethod: '场外',
    isTop3: true,
  },
  {
    id: '4',
    name: '朱少醒',
    fundName: '富国天惠成长混合A',
    fundCode: '161005',
    years: 18.5,
    annualizedReturn: 15.6,
    maxDrawdown: -58.9,
    philosophy: '均衡成长，淡化择时，长期坚守优秀企业',
    stockSelectionLogic: '偏好具有优秀企业基因、管理层靠谱、能在长跑中胜出的公司，容忍短期波动，高仓位运作。',
    holdings: ['贵州茅台', '宁德时代', '迈瑞医疗'],
    tradingMethod: '场内/场外',
  },
  {
    id: '5',
    name: '谢治宇',
    fundName: '兴全合润混合',
    fundCode: '163406',
    years: 13.2,
    annualizedReturn: 16.1,
    maxDrawdown: -42.1,
    philosophy: '均衡配置，寻找性价比高的优质资产',
    stockSelectionLogic: '在不同行业中比较风险收益比，不押注单一赛道，寻找估值与成长性匹配的标的。',
    holdings: ['海尔智家', '三安光电', '双汇发展'],
    tradingMethod: '场内/场外',
  },
  {
    id: '6',
    name: '张坤',
    fundName: '易方达优质精选（原中小盘）',
    fundCode: '110011',
    years: 13.5,
    annualizedReturn: 15.1,
    maxDrawdown: -55.2,
    philosophy: '优质商业模式，高ROE，长期集中持有',
    stockSelectionLogic: '寻找具有强大护城河、高ROE、能产生大量自由现金流的商业模式，伴随企业成长，极少换手。',
    holdings: ['腾讯控股', '五粮液', '泸州老窖'],
    tradingMethod: '场外',
  },
  {
    id: '7',
    name: '周蔚文',
    fundName: '中欧新蓝筹A',
    fundCode: '166002',
    years: 12.5,
    annualizedReturn: 15.2,
    maxDrawdown: -28.5,
    philosophy: '行业景气度投资，寻找左侧拐点，长期持有',
    stockSelectionLogic: '寻找未来2-3年行业景气度向上的板块，在其中挑选盈利增长确定性高的龙头企业。',
    holdings: ['牧原股份', '紫金矿业', '万华化学'],
    tradingMethod: '场内/场外',
  },
  {
    id: '8',
    name: '刘彦春',
    fundName: '景顺长城鼎益A',
    fundCode: '162605',
    years: 10.5,
    annualizedReturn: 15.8,
    maxDrawdown: -52.3,
    philosophy: '聚焦消费和医药，做时间的朋友',
    stockSelectionLogic: '偏好高投入资本回报率、高毛利的行业龙头，看重企业的定价权和品牌壁垒。',
    holdings: ['泸州老窖', '迈瑞医疗', '古井贡酒'],
    tradingMethod: '场内/场外',
  },
  {
    id: '9',
    name: '王崇',
    fundName: '交银新成长',
    fundCode: '519736',
    years: 11.8,
    annualizedReturn: 16.2,
    maxDrawdown: -38.5,
    philosophy: '寻找具有良好商业模式的成长股',
    stockSelectionLogic: '竞争格局清晰、估值合理，看重企业的内生增长动力和管理层执行力，注重回撤控制。',
    holdings: ['紫光国微', '中航光电', '宁德时代'],
    tradingMethod: '场外',
  },
  {
    id: '10',
    name: '萧楠',
    fundName: '易方达消费行业',
    fundCode: '110022',
    years: 13.5,
    annualizedReturn: 15.4,
    maxDrawdown: -45.6,
    philosophy: '深度研究消费品商业模式，长期持有',
    stockSelectionLogic: '寻找具备定价权和品牌壁垒的企业，看重自由现金流和股东回报，对消费品有极深理解。',
    holdings: ['山西汾酒', '贵州茅台', '五粮液'],
    tradingMethod: '场外',
  },
  {
    id: '11',
    name: '何帅',
    fundName: '交银优势行业',
    fundCode: '519697',
    years: 10.5,
    annualizedReturn: 16.3,
    maxDrawdown: -31.2,
    philosophy: '寻找持续成长且估值未被充分挖掘的隐形冠军',
    stockSelectionLogic: '偏好细分行业龙头，看重企业的内生增长动力和管理层执行力，追求绝对收益。',
    holdings: ['爱尔眼科', '泰格医药', '药明康德'],
    tradingMethod: '场外',
  }
];
